sudo: require
dist: beaver
language: generic

cache:
directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
  
timeout: 3600

before_install:
  - travis_wait 45 bash ./utilities/travis_setup.sh
  - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"

script:
  - mkdir _build
  - latexmk -pdf -interaction=nonstopmode -halt-on-error src/SiddharthCV.tex
  - latexmk -c
