sudo: required
dist: beaver
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends dvipng miktex
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build src/SiddharthCV.tex
