sudo: require
dist: beaver
language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build src/SiddharthCV.tex
