sudo: required
language: generic
dist: bionic
services: docker

before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
- pdflatex -interaction=nonstopmode -halt-on-error src/SiddharthCV.tex
