sudo: required
language: latex

services:
  - docker

script:
  - docker pull rekka/tectonic
  - docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind rekka/tectonic tectonic SiddharthCV.tex
