sudo: required
language: latex

before_install:
- sudo apt-get update -qq
- sudo apt-get install texlive-latex-base
script:
- mkdir build
- pdflatex -output-directory build src/SiddharthCV.tex
deploy:
  provider: releases
  file:
    - build/SiddharthCV.pdf
  skip_cleanup: true
  on:
    tags: true
