sudo: require
dist: beaver
language: generic

before_install:
- sudo apt-get update -qq
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
- echo "deb http://miktex.org/download/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list
- sudo apt-get update
- sudo apt-get install -f miktex

script:
  - latexmk -pdf -interaction=nonstopmode -halt-on-error src/SiddharthCV.tex
  - latexmk -c
